import Footer from "@/components/Footer";
import "./globals.css";
import Header from "@/components/Header";
import { AppProvider, useAppContext } from "@/Context";
import AnimatedLink from "@/components/AnimatedLink";
import { PulsatingButton } from "@/components/ui/pulsating-button";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          id="Cookiebot"
          src="https://consent.cookiebot.com/uc.js"
          data-cbid="cc27d4d8-4b44-42c0-9975-8242000510db"
          type="text/javascript"
          async
        ></script>
      </head>
      <AppProvider>
        <body className="dark mt-[22vh]">
          <Header />
          {children}
          <Footer />
        </body>
      </AppProvider>
    </html>
  );
}
