import Footer from "@/components/Footer";
import "./globals.css";
import Header from "@/components/Header";
import { AppProvider, useAppContext } from "@/Context";
import AnimatedLink from "@/components/AnimatedLink";
import { PulsatingButton } from "@/components/ui/pulsating-button";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-8075XGQXG3"
        ></script>
        <script>
          window.dataLayer = window.dataLayer || []; function gtag()
          {dataLayer.push(arguments)}
          gtag('js', new Date()); gtag('config', 'G-8075XGQXG3');
        </script>
      </head>
      <AppProvider>
        <body className="dark mt-[22vh]">
          <Header />
          {children}
          <Footer />
        </body>
      </AppProvider>
    </html>
  );
}
